### ISSUE TITLE
puplic email provider will not accept email from pi-star

### ISSUE THREAD

**Issue by hans-dot** [K2IE/dapgw2email#2]
How did you solve the problem that no public internet provider will accept mails from pi-star?
I think a solution could be to install an email server on pi-star itself.
What is your solution? Why not just write the output in a text file?

**Comment by K2IE** [comment]
This was addressed.

You can now use any email provider that supports authsmtp over SSL on port 465.  Be sure to put a firewall rule in Pi-Star's /root/ipv4.fw to allow the outbound connection, whether you opt to use port 25 (unauthenticated) or this new option.
